### PR TITLE
FlattenRegionStreamHashImageFilter post merge stuff

### PR DESCRIPTION
**Pull request by tad1**
## Description
see #711

### **check if flatten work with compressed textures**
In 24th example right after loading texture I've applied flatten filter, and used output image for the rest of program - displaying works; hashing passes (content hash for output image from CFlattenRegionsImageFilter is not set - we get zero hash instead - works fine after recalculating content hash).
Tested against Block Compression (BC1,BC3,BC7)

## TODO list:
- [x] remove unused variables
- [x] ICPUBuffer to corresponding span
- [x] move code from assert
- [x] check if flatten work with compressed textures
- [x] zero-lenght hash
- [x] iota -> custom iterator

### CODE REVIEW

**Comment by tad1** [comment]
where definition of `ValueIterator` should be located?

**Comment by devshgraphicsprogramming** [comment]
> where the definition of `ValueIterator` should be located?

if you just need an iterator that goes over integers from `S` to `S+N` there's https://en.cppreference.com/w/cpp/ranges/iota_view

**Comment by devshgraphicsprogramming** [comment]
Why do I see my own changes again?

**Comment by devshgraphicsprogramming** [comment]
I still see my own changes, start a new branch from my HEAD, cherry pick your commits and learn to pull/merge properly.

**Comment by tad1** [comment]
> I still see my own changes, start a new branch from my HEAD, cherry pick your commits and learn to pull/merge properly.

fixed this branch instead

**Pull request merged**
