### PR TITLE
libjpeg-turbo

### PR DESCRIPTION
**Pull request by AnastaZIuk**
we need to consider what to checkbox 
image

### CODE REVIEW

**Comment by devshgraphicsprogramming** [comment]
definitely **not** checked:
- crt dll
- fuzz
- java

no clues about the 12bit jpeg

**Comment by devshgraphicsprogramming** [comment]
@Crisspl decide when and how to merge

**Comment by AnastaZIuk** [comment]
disclaimer, not to merge yet

**Comment by AnastaZIuk** [comment]
@Crisspl ready to merge

**Comment by devshgraphicsprogramming** [comment]
@AnastaZIuk did you remove the old jpeg library submodule?

**Comment by AnastaZIuk** [comment]
> @AnastaZIuk did you remove the old jpeg library submodule?

yup, it won't be seen after new clone https://github.com/Devsh-Graphics-Programming/Nabla/pull/139/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584L43

**Comment by devshgraphicsprogramming** [comment]
> @Crisspl ready to merge

has my blessing

**Pull request merged**
