### PR TITLE
CommonAPI and Examples Changes + Acceleration Structure Work and RayQueryExample

### PR DESCRIPTION
**Pull request by Erfan-Ahmadi**
## Description
Some new changes:

- CommonAPI Init function changed and now gets input for Extensions
- CommonAPI output for Init function changed and templated stuff is removed
- Shader Stage Enum moved to new namespace
- RayQuery Example and Acceleration Structure Added 
- Added "allocateFlags" to DriverAllocation
- Stuff I may not remember at the moment of writing xD

## TODO list:
[x] Make sure All Examples Compile and Run as Expected
[x] Make sure Examples and Engines for Android Compiles and Runs as Expected (Need @AnastaZIuk's help)

01
02 [DONE]
06 [DONE]
07 [DONE]
09 [DONE]
11 [DONE]
12 [DONE]
14 [DONE]
16 [DONE]
17 [DONE]
20
27 [STILL HAS MAIN.CPP -> Needs Some Love Later]
29
33
35
38 [STILL HAS MAIN.CPP -> Needs Some Love Later]
42 [WORKS] [STILL HAS MAIN.CPP -> Needs Some Love Later]
48 [DONE]
52 [Doesn't USE CommonAPI] [MAY NEED SOME FIXES] [CRASHES?]
54 [DONE]
55 [DONE]
56 [DONE]
57 [Doesn't USE CommonAPI] [MAY NEED SOME FIXES]
58 [Doesn't USE CommonAPI] [MAY NEED SOME FIXES]

### CODE REVIEW

**Comment by AnastaZIuk** [comment]
@Erfan-Ahmadi we have a lot of glTF compile errors, please make sure you have all @devshgraphicsprogramming's changes from `animation` branch and then I can continue investigating

**Comment by Erfan-Ahmadi** [comment]
Already merged into newAPI branches

**Comment by devshgraphicsprogramming** [comment]
> Already merged into newAPI branches

@Erfan-Ahmadi in that case, can the `erfan_vulkan_as` branch be deleted?

**Comment by Erfan-Ahmadi** [comment]
Yes!

**Pull request closed without merging**
